import Header from "../components/Header";
import styles from "./page.module.css";

export default function ActivitiesPage() {
return <main className={styles.page}><Header /><section className={styles.section}><h2 className={styles.title}>Activities</h2>

<div className={styles.block}><div className={styles.imageWrap}><img src="/MAK.png" alt="Mind, Art, Knowledge conference" className={styles.image} /></div><div className={styles.textCol}><p className={styles.meta}><b>16 June 2026 — Brussels, Belgium</b><br />Mind, Art, Knowledge: Dialogues Between Cognitive Science, Artistic Practice And Philosophy</p><p className={styles.p}><b>Attending to the Irrelevant: How the Mind Makes Sense of Poetry</b></p><p className={styles.p}>In this keynote lecture, I discussed how people make sense of poetic language. Drawing on the work of Roman Jakobson, I examined how poetic techniques can change the way readers attend to and interpret language. The talk presented research using semantic distance, surprisal, and eye-tracking to investigate how people process semantically distant word combinations in poetry.</p><p className={styles.p}>I also discussed how rhyme and line breaks influence attention and interpretation, and how poetic framing can encourage readers to search for meaning beyond literal interpretations. This work connects poetic language with broader questions about creativity and meaning-making.</p></div></div>

<div className={styles.block}><div className={styles.textCol}><p className={styles.meta}><b>Art in Conversation</b></p><p className={styles.p}>I co-organised the interdisciplinary <a href="https://artinconversation.wp.st-andrews.ac.uk/" target="_blank" rel="noopener noreferrer" className={styles.linkInline}>Art in Conversation</a> seminar series with Dr Nicole Ruta at the University of St Andrews.</p><p className={styles.p}>The series brought together researchers from different academic disciplines, artists, and cultural practitioners to discuss art from multiple perspectives. The programme included discussions of topics such as the sublime, embodied cognition, imagination, and synaesthesia.</p><p className={styles.p}>The seminars were held online and made available to a wider audience through recorded talks and video interviews with participating researchers and practitioners.</p></div><div className={styles.imageWrap}><img src="/artinconv.png" alt="Art in Conversation seminar" className={styles.image} /><img src="/artyoutube.png" alt="Art in Conversation online platform" className={styles.image} /></div></div>

<div className={styles.block}><div className={styles.imageWrap}><img src="/VSAC.png" alt="Visual Science of Art conference" className={styles.image} /></div><div className={styles.textCol}><p className={styles.meta}><b>23 August 2025 — Wiesbaden, Germany</b><br />Visual Science of Art Conference (VSAC)</p><p className={styles.p}><b>When Objects Become Art: The Power of Context</b></p><p className={styles.p}>I presented research examining how context changes the way people perceive and interpret objects. The research used experimental manipulations in which identical objects were presented either as artworks or as ordinary objects.</p><p className={styles.p}>The findings showed that presenting an object as art can change the meanings people attribute to it and encourage interpretations that go beyond its literal or everyday function.</p></div></div>

<div className={styles.block}><div className={styles.textCol}><p className={styles.meta}><b>21–23 May 2025 — Paris, France</b><br />Society for the Neuroscience of Creativity</p><p className={styles.p}><b>Do creativity and psychosis proneness share similar mechanisms in visual salience allocation?</b></p><p className={styles.p}>I presented research investigating whether creative individuals and individuals with psychosis-proneness show similarities in the way they allocate visual attention and identify salient information.</p><p className={styles.p}>The project examined the relationship between creativity, unusual patterns of thinking, and visual salience attribution.</p></div><div className={styles.imageWrap}><img src="/Creativity.png" alt="Creativity conference presentation" className={styles.image} /><img src="/creativity2.png" alt="Creativity research" className={styles.image} /></div></div>

<div className={styles.block}><div className={styles.imageWrap}><img src="/iconmary.jpeg" alt="Religious art conference" className={styles.image} /></div><div className={styles.textCol}><p className={styles.meta}><b>2–4 November 2023 — Turin, Italy</b><br />Second International Conference on Beauty and Change</p><p className={styles.p}>I presented research examining psychological distance and the experience of religious art.</p><p className={styles.p}>The research investigated how people experience and interpret religious artworks and how psychological distance can influence their engagement with visual representations.</p></div></div>

<div className={styles.block}><div className={styles.textCol}><p className={styles.meta}><b>August 2020 — Amsterdam, Netherlands</b><br />Visual Science of Art Conference (VSAC)</p><p className={styles.p}>I presented research examining how perceptual context influences the interpretation of everyday objects and artworks.</p><p className={styles.p}>The research was inspired by ready-made art and examined how the same object can be interpreted differently depending on whether it is presented as part of everyday life or as an artwork.</p></div><div className={styles.imageWrap}><img src="/carrotonthewall.jpeg" alt="VSAC 2020 presentation" className={styles.image} /></div></div>

<div className={styles.block}><div className={styles.textCol}><p className={styles.meta}><b>17–20 October 2019 — Moscow, Russia</b><br />Synaesthesia: Cross-sensory Aspects of Cognition across Science and Art</p><p className={styles.p}>I presented research on cross-modal associations between cinematic aesthetics and tactile sensations.</p><p className={styles.p}>The study examined how experiences of beauty and ugliness in cinema can become associated with different tactile sensations, and the role of emotional and semantic mechanisms in these associations.</p></div></div>

<div className={styles.block}><div className={styles.imageWrap}><img src="/Moscow.png" alt="Moscow Cognitive Science Seminar" className={styles.image} /><img src="/coglab.png" alt="Cognitive science laboratory" className={styles.image} /></div><div className={styles.textCol}><p className={styles.meta}><b>December 2016 — Moscow, Russia</b><br />Moscow Cognitive Science Seminar</p><p className={styles.p}><b>Emotions mediate associations between haptic perception and cinematic aesthetics</b></p><p className={styles.p}>I presented research investigating associations between tactile perception and cinematic aesthetics, focusing on the role of emotional experience in connecting information across sensory modalities.</p><p className={styles.p}><a href="https://www.youtube.com/" target="_blank" rel="noopener noreferrer" className={styles.linkInline}>Video of the talk</a></p></div></div>

<div className={styles.block}><div className={styles.textCol}><p className={styles.meta}><b>August 2015 — Liverpool, UK</b><br />Visual Science of Art Conference (VSAC)</p><p className={styles.p}><b>The perception of beauty and ugliness in the cinema: a pilot study</b></p><p className={styles.p}>I presented a pilot study examining the perception of beauty and ugliness in cinema. The research investigated associations between cinematic aesthetics, tactile sensations, emotions, and semantic evaluations.</p></div></div>

</section></main>;
}
